import 'dart:async';

/// Types of events that the SDK can generate.
enum EventType {
  appCreateComplete,
  appLocked,
  appUnlocked,
  loginComplete,
  mainActivityCreateComplete,
  logoutComplete,
  userSwitched,
  refreshTokenRevoked,
  other,
}

/// Represents an SDK event with a type and optional data.
class SdkEvent {
  /// The type of event.
  final EventType type;

  /// Optional data associated with the event.
  final Object? data;

  SdkEvent(this.type, [this.data]);

  @override
  String toString() => 'SdkEvent($type${data != null ? ', $data' : ''})';
}

/// Observer interface for SDK events.
abstract class EventsObserver {
  void onEvent(SdkEvent event);
}

/// Global event bus for SDK lifecycle events.
///
/// Allows components (primarily test classes) to register and receive
/// events generated by the SDK. Uses both an observer pattern and
/// a Dart [Stream] for flexibility.
class EventsObservable {
  static final EventsObservable _instance = EventsObservable._internal();

  final List<EventsObserver> _observers = [];
  final StreamController<SdkEvent> _controller =
      StreamController<SdkEvent>.broadcast();

  EventsObservable._internal();

  /// Returns the singleton instance.
  static EventsObservable get instance => _instance;

  /// A broadcast stream of all SDK events.
  Stream<SdkEvent> get eventStream => _controller.stream;

  /// Registers an observer to receive events.
  void registerObserver(EventsObserver observer) {
    if (!_observers.contains(observer)) {
      _observers.add(observer);
    }
  }

  /// Unregisters an observer.
  void unregisterObserver(EventsObserver observer) {
    _observers.remove(observer);
  }

  /// Unregisters all observers.
  void unregisterAll() {
    _observers.clear();
  }

  /// Notifies all observers and the stream of an event.
  void notifyEvent(EventType type, [Object? data]) {
    final event = SdkEvent(type, data);
    for (final observer in List.of(_observers)) {
      observer.onEvent(event);
    }
    if (!_controller.isClosed) {
      _controller.add(event);
    }
  }
}
