name: Nightly Tests

on:
  schedule:
    - cron: "30 6 * * 2-6"  # cron is UTC; 10:30 PM PT every weekday (Mon-Fri).
  # This lets us trigger the workflow from a browser.
  workflow_dispatch:

permissions:
  contents: read

# Run the native libraries first so that the native and Hybrid MobileSync tests
# don't run simultaneously (to prevent flappers).
jobs:
  android-nightly:
    permissions:
      contents: read
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        lib: [SalesforceAnalytics, SalesforceSDK, SmartStore, MobileSync]
    uses: ./.github/workflows/reusable-lib-workflow.yaml
    with:
      lib: ${{ matrix.lib }}
    secrets:
      TEST_CREDENTIALS: ${{ secrets.TEST_CREDENTIALS }}
      GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  android-nightly-Hybrid:
    permissions:
      contents: read
      pull-requests: write
    if: success() || failure()
    needs: [android-nightly]
    strategy:
      fail-fast: false
      matrix:
        lib: [SalesforceHybrid]
    uses: ./.github/workflows/reusable-lib-workflow.yaml
    with:
      lib: ${{ matrix.lib }}
    secrets:
      TEST_CREDENTIALS: ${{ secrets.TEST_CREDENTIALS }}
      GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  android-nightly-UI-Tests:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/reusable-ui-workflow.yaml
    secrets:
      MSDK_ANDROID_REMOTE_ACCESS_CALLBACK_URL: ${{ secrets.MSDK_ANDROID_REMOTE_ACCESS_CALLBACK_URL }}
      MSDK_ANDROID_REMOTE_ACCESS_CONSUMER_KEY: ${{ secrets.MSDK_ANDROID_REMOTE_ACCESS_CONSUMER_KEY }}
      UI_TEST_CONFIG: ${{ secrets.UI_TEST_CONFIG }}
      GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
